# # Person.create!([
#   {first_name: "Art", last_name: "Crist", email: "crist_art@yahoo.com", phone_number: "665-666-5153 x569", middle_name: nil, bio: nil},
#   {first_name: "Guido", last_name: "Mueller", email: "guido.mueller@yahoo.com", phone_number: "379-475-6144 x28960", middle_name: nil, bio: nil},
#   {first_name: "Lila", last_name: "Lehner", email: "lehner_lila@gmail.com", phone_number: "954.701.1975 x9133", middle_name: nil, bio: nil},
#   {first_name: "Kylie", last_name: "Weber", email: "weber.kylie@hotmail.com", phone_number: "607.166.1656 x876", middle_name: nil, bio: nil},
#   {first_name: "Jay", last_name: "Will", email: "will.jay@gmail.com", phone_number: "(462) 130-0751 x908", middle_name: nil, bio: nil},
#   {first_name: "Freida", last_name: "Schimmel", email: "freida_schimmel@yahoo.com", phone_number: "119.110.9555", middle_name: nil, bio: nil},
#   {first_name: "Yasmin", last_name: "Hoeger", email: "yasmin_hoeger@hotmail.com", phone_number: "690.358.0049 x5202", middle_name: nil, bio: nil},
#   {first_name: "Marvin", last_name: "Braun", email: "braun_marvin@hotmail.com", phone_number: "192.787.6264", middle_name: nil, bio: nil},
#   {first_name: "Erik", last_name: "Braun", email: "erik.braun@hotmail.com", phone_number: "182.726.0590", middle_name: nil, bio: nil},
#   {first_name: "Kaleigh", last_name: "McDermott", email: "kaleigh.mcdermott@gmail.com", phone_number: "1-371-140-5871 x08502", middle_name: nil, bio: nil},
#   {first_name: "Gisselle", last_name: "Hagenes", email: "hagenes.gisselle@gmail.com", phone_number: "566-802-0542", middle_name: nil, bio: nil},
#   {first_name: "Furman", last_name: "Bradtke", email: "bradtke_furman@hotmail.com", phone_number: "(306) 761-4694 x5241", middle_name: nil, bio: nil},
#   {first_name: "Cynthia", last_name: "Feil", email: "cynthia.feil@hotmail.com", phone_number: "724.152.6465 x97002", middle_name: nil, bio: nil},
#   {first_name: "Afton", last_name: "Stanton", email: "afton.stanton@hotmail.com", phone_number: "348.913.1575 x715", middle_name: nil, bio: nil},
#   {first_name: "Janet", last_name: "Swaniawski", email: "swaniawski.janet@yahoo.com", phone_number: "1-104-954-0214", middle_name: nil, bio: nil},
#   {first_name: "Wendy", last_name: "Beer", email: "wendy_beer@hotmail.com", phone_number: "285-066-4343", middle_name: nil, bio: nil},
#   {first_name: "Burdette", last_name: "Hamill", email: "hamill.burdette@yahoo.com", phone_number: "1-995-903-5951 x97716", middle_name: nil, bio: nil},
#   {first_name: "Coby", last_name: "Schoen", email: "schoen.coby@gmail.com", phone_number: "1-938-091-1827", middle_name: nil, bio: nil},
#   {first_name: "Montana", last_name: "West", email: "west_montana@yahoo.com", phone_number: "(560) 786-5833 x0112", middle_name: nil, bio: nil},
#   {first_name: "Demarcus", last_name: "Witting", email: "witting_demarcus@yahoo.com", phone_number: "(561) 149-4617 x53301", middle_name: nil, bio: nil},
#   {first_name: "Caesar", last_name: "Dickinson", email: "dickinson.caesar@gmail.com", phone_number: "624.176.8302 x6461", middle_name: nil, bio: nil},
#   {first_name: "Arlene", last_name: "Labadie", email: "labadie_arlene@yahoo.com", phone_number: "1-642-298-3110", middle_name: nil, bio: nil},
#   {first_name: "Colby", last_name: "Eichmann", email: "colby_eichmann@yahoo.com", phone_number: "(575) 106-3638 x368", middle_name: nil, bio: nil},
#   {first_name: "Catalina", last_name: "Parker", email: "catalina.parker@yahoo.com", phone_number: "(296) 149-9899", middle_name: nil, bio: nil},
#   {first_name: "Lurline", last_name: "Kassulke", email: "lurline.kassulke@gmail.com", phone_number: "1-790-128-9240", middle_name: nil, bio: nil},
#   {first_name: "Lawson", last_name: "Towne", email: "lawson.towne@yahoo.com", phone_number: "406-616-3886", middle_name: nil, bio: nil},
#   {first_name: "Marshall", last_name: "Wintheiser", email: "marshall.wintheiser@yahoo.com", phone_number: "982.146.7224 x986", middle_name: nil, bio: nil},
#   {first_name: "Drew", last_name: "Turner", email: "drew.turner@yahoo.com", phone_number: "708-648-4737 x995", middle_name: nil, bio: nil},
#   {first_name: "Susanna", last_name: "Lubowitz", email: "lubowitz_susanna@hotmail.com", phone_number: "989-156-0622 x9944", middle_name: nil, bio: nil},
#   {first_name: "Laura", last_name: "Green", email: "laura_green@hotmail.com", phone_number: "1-625-740-2605", middle_name: nil, bio: nil},
#   {first_name: "Alisha", last_name: "Johnson", email: "alisha.johnson@hotmail.com", phone_number: "615-528-1147", middle_name: nil, bio: nil},
#   {first_name: "Preston", last_name: "Bode", email: "bode.preston@yahoo.com", phone_number: "920-235-3575", middle_name: nil, bio: nil},
#   {first_name: "Lilliana", last_name: "Mertz", email: "mertz_lilliana@gmail.com", phone_number: "584-449-4074 x95033", middle_name: nil, bio: nil},
#   {first_name: "Kailyn", last_name: "Cartwright", email: "kailyn.cartwright@gmail.com", phone_number: "(331) 017-5621", middle_name: nil, bio: nil},
#   {first_name: "Sage", last_name: "Farrell", email: "sage_farrell@hotmail.com", phone_number: "899.519.2000", middle_name: nil, bio: nil},
#   {first_name: "Gregorio", last_name: "Kirlin", email: "kirlin_gregorio@hotmail.com", phone_number: "(403) 074-2893 x493", middle_name: nil, bio: nil},
#   {first_name: "Ernestina", last_name: "Considine", email: "considine.ernestina@hotmail.com", phone_number: "473.017.1514 x59653", middle_name: nil, bio: nil},
#   {first_name: "Harvey", last_name: "Jenkins", email: "harvey.jenkins@gmail.com", phone_number: "1-199-372-4411 x392", middle_name: nil, bio: nil},
#   {first_name: "Jordane", last_name: "Cummerata", email: "jordane_cummerata@hotmail.com", phone_number: "534.910.7626", middle_name: nil, bio: nil},
#   {first_name: "Lois", last_name: "Bauch", email: "lois_bauch@gmail.com", phone_number: "(873) 342-1739", middle_name: nil, bio: nil},
#   {first_name: "Jimmy", last_name: "Roob", email: "jimmy.roob@yahoo.com", phone_number: "271.606.9174", middle_name: nil, bio: nil},
#   {first_name: "Nicholaus", last_name: "Heathcote", email: "heathcote_nicholaus@gmail.com", phone_number: "883-513-9082 x623", middle_name: nil, bio: nil},
#   {first_name: "Albin", last_name: "Corkery", email: "corkery.albin@gmail.com", phone_number: "864.047.4908", middle_name: nil, bio: nil},
#   {first_name: "Callie", last_name: "Connelly", email: "callie_connelly@hotmail.com", phone_number: "(802) 736-7249 x282", middle_name: nil, bio: nil},
#   {first_name: "Hoyt", last_name: "Emmerich", email: "emmerich_hoyt@hotmail.com", phone_number: "550-457-7122 x8241", middle_name: nil, bio: nil},
#   {first_name: "Luisa", last_name: "Cummings", email: "cummings_luisa@gmail.com", phone_number: "830.537.7036 x42217", middle_name: nil, bio: nil},
#   {first_name: "Kirsten", last_name: "Harber", email: "harber_kirsten@gmail.com", phone_number: "249.175.5237 x468", middle_name: nil, bio: nil},
#   {first_name: "Eloy", last_name: "Murazik", email: "eloy.murazik@yahoo.com", phone_number: "1-884-709-0065", middle_name: nil, bio: nil},
#   {first_name: "Evangeline", last_name: "Klein", email: "evangeline.klein@gmail.com", phone_number: "(492) 000-6795 x046", middle_name: nil, bio: nil},
#   {first_name: "Elmore", last_name: "White", email: "elmore_white@hotmail.com", phone_number: "374.337.7625", middle_name: nil, bio: nil},
#   {first_name: "Jedidiah", last_name: "Stroman", email: "jedidiah.stroman@hotmail.com", phone_number: "806-936-2326 x29761", middle_name: nil, bio: nil},
#   {first_name: "Duncan", last_name: "Bahringer", email: "bahringer_duncan@gmail.com", phone_number: "228-877-5635", middle_name: nil, bio: nil},
#   {first_name: "Emerson", last_name: "Wyman", email: "wyman_emerson@gmail.com", phone_number: "1-131-919-9351 x4816", middle_name: nil, bio: nil},
#   {first_name: "Katlynn", last_name: "Zboncak", email: "katlynn.zboncak@hotmail.com", phone_number: "1-781-414-3073 x95213", middle_name: nil, bio: nil},
#   {first_name: "Bruce", last_name: "Christiansen", email: "christiansen_bruce@gmail.com", phone_number: "178-988-8268", middle_name: nil, bio: nil},
#   {first_name: "Elaina", last_name: "Nicolas", email: "nicolas_elaina@hotmail.com", phone_number: "674-102-5462 x77687", middle_name: nil, bio: nil},
#   {first_name: "Claudia", last_name: "Herzog", email: "claudia_herzog@yahoo.com", phone_number: "1-873-224-2829", middle_name: nil, bio: nil},
#   {first_name: "Ayla", last_name: "Cormier", email: "cormier_ayla@gmail.com", phone_number: "353-026-4873 x96014", middle_name: nil, bio: nil},
#   {first_name: "Quincy", last_name: "Johnston", email: "johnston_quincy@hotmail.com", phone_number: "659.087.3201", middle_name: nil, bio: nil},
#   {first_name: "Micah", last_name: "Hoppe", email: "hoppe_micah@gmail.com", phone_number: "587.147.1935 x804", middle_name: nil, bio: nil},
#   {first_name: "Maynardwoo", last_name: "Nicolas", email: "nicolas_maynard@gmail.com", phone_number: "703.049.7141 x8264", middle_name: nil, bio: nil},
#   {first_name: "Raven", last_name: "Kling", email: "kling.raven@hotmail.com", phone_number: "927.736.0336 x64303", middle_name: nil, bio: nil},
#   {first_name: "Elyse", last_name: "Fadel", email: "fadel_elyse@yahoo.com", phone_number: "528-561-3503 x89656", middle_name: nil, bio: nil},
#   {first_name: "Omari", last_name: "Russel", email: "omari.russel@yahoo.com", phone_number: "1-704-383-6967", middle_name: nil, bio: nil},
#   {first_name: "Arianna", last_name: "Kohler", email: "kohler_arianna@gmail.com", phone_number: "1-407-019-5426", middle_name: nil, bio: nil},
#   {first_name: "Amparo", last_name: "Smitham", email: "smitham_amparo@gmail.com", phone_number: "1-902-439-6846 x686", middle_name: nil, bio: nil},
#   {first_name: "Savanna", last_name: "Hansen", email: "savanna_hansen@yahoo.com", phone_number: "818.726.3998", middle_name: nil, bio: nil},
#   {first_name: "Van", last_name: "Davis", email: "davis_van@hotmail.com", phone_number: "262.145.1813 x6754", middle_name: nil, bio: nil},
#   {first_name: "Nona", last_name: "Botsford", email: "nona.botsford@gmail.com", phone_number: "929.794.6764", middle_name: nil, bio: nil},
#   {first_name: "Orion", last_name: "Russel", email: "orion.russel@hotmail.com", phone_number: "949-421-1780 x31091", middle_name: nil, bio: nil},
#   {first_name: "Joany", last_name: "Crooks", email: "crooks.joany@yahoo.com", phone_number: "1-333-322-5871 x40497", middle_name: nil, bio: nil},
#   {first_name: "Loyce", last_name: "King", email: "king_loyce@gmail.com", phone_number: "160-882-9591", middle_name: nil, bio: nil},
#   {first_name: "Justice", last_name: "Yost", email: "yost_justice@hotmail.com", phone_number: "1-357-617-6764 x619", middle_name: nil, bio: nil},
#   {first_name: "Brando", last_name: "Balistreri", email: "brando.balistreri@gmail.com", phone_number: "1-930-358-0775", middle_name: nil, bio: nil},
#   {first_name: "Omari", last_name: "D'Amore", email: "d.omari.amore@gmail.com", phone_number: "482.451.9911", middle_name: nil, bio: nil},
#   {first_name: "Elisa", last_name: "Ruecker", email: "elisa_ruecker@gmail.com", phone_number: "143-907-6480", middle_name: nil, bio: nil},
#   {first_name: "Shannon", last_name: "Schuppe", email: "schuppe_shannon@gmail.com", phone_number: "886-997-0587", middle_name: nil, bio: nil},
#   {first_name: "Georgette", last_name: "Brekke", email: "georgette.brekke@hotmail.com", phone_number: "763-522-0897", middle_name: nil, bio: nil},
#   {first_name: "Lavinia", last_name: "Kovacek", email: "kovacek.lavinia@hotmail.com", phone_number: "935.963.7453 x67667", middle_name: nil, bio: nil},
#   {first_name: "Chelsea", last_name: "Schamberger", email: "schamberger.chelsea@hotmail.com", phone_number: "1-621-176-7312 x77944", middle_name: nil, bio: nil},
#   {first_name: "Gilbert", last_name: "Huels", email: "gilbert_huels@hotmail.com", phone_number: "1-992-756-4477 x594", middle_name: nil, bio: nil},
#   {first_name: "Mae", last_name: "Kerluke", email: "mae_kerluke@yahoo.com", phone_number: "415.379.1189 x446", middle_name: nil, bio: nil},
#   {first_name: "Alta", last_name: "Williamson", email: "alta_williamson@yahoo.com", phone_number: "(844) 595-5993 x7851", middle_name: nil, bio: nil},
#   {first_name: "Joany", last_name: "Bins", email: "bins.joany@hotmail.com", phone_number: "204.566.4196 x29064", middle_name: nil, bio: nil},
#   {first_name: "Marley", last_name: "Marks", email: "marley.marks@yahoo.com", phone_number: "592.976.4031", middle_name: nil, bio: nil},
#   {first_name: "Reagan", last_name: "Rath", email: "rath_reagan@hotmail.com", phone_number: "1-282-966-5232 x958", middle_name: nil, bio: nil},
#   {first_name: "Keith", last_name: "Boyer", email: "boyer.keith@gmail.com", phone_number: "438.705.6325 x5889", middle_name: nil, bio: nil},
#   {first_name: "Billie", last_name: "Schulist", email: "billie_schulist@hotmail.com", phone_number: "778-449-6060", middle_name: nil, bio: nil},
#   {first_name: "Jalyn", last_name: "McGlynn", email: "mcglynn_jalyn@hotmail.com", phone_number: "(697) 816-7534 x285", middle_name: nil, bio: nil},
#   {first_name: "asdfa", last_name: "asdkfja", email: "asdlkfj", phone_number: "alskdjfa;sldja;", middle_name: nil, bio: nil}
# ])


# Group.create([
  #             {name: "Friends" },
  #             {name: "Coworkers"},
  #             {name: "Family"},
  #             {name: "Professors"},
  #             {name: "Kings"}

  # ])

# id_list = Person.all.map {|per| per.id}
# group_id = Group.all.map {|g_id| g_id.id}

# id_list.each do |id|
#   group_id.sample(rand(1..3)).each do |g_id|
#     PersonGroup.create!(group_id: g_id, person_id: id)
#   end
# end