# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 677a5601d33c83149f72967f690cd336a03d07bbfd700060daae0e32b43f9a1ec528150b665d3ba719f94a20665c531d136c854a9efeb9d1bdd1b70aabf30233

test:
  secret_key_base: 069daccb7e1d029f9fbb4f981dcf08486a306c5c6d6a4e1cf44987ed79f7b753e0ae2a38ea31dd026530776bfa488b6d9a492fb4496cffbf8aed013e66817c58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
