# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa3ee393d206efce54b7afa67680440d4a561e0efd5e0ef2553a4da4e74020b513695a1a051e916d3ed8044a94b3af5f1fc698a4809c6e401a86ad0cabc98e95

test:
  secret_key_base: 479f37fde0ad9ea1bed28f6e144acb3145d29845e64016e613b618b23a4d70dfb653d07485fba0ea17d6d4cefdf8fe86450b40067691e4b199fc305b9ac07640

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
